package entity;

public class DonutOrder {
    private int transactionId; // generated by DB
    private String orderDateTime; // stored as timestamp string
    private String itemsDetails;
    private double subtotal;
    private double taxAmount;
    private double totalAmount;

    public DonutOrder(int transactionId, String orderDateTime, String itemsDetails,
                      double subtotal, double taxAmount, double totalAmount) {
        this.transactionId = transactionId;
        this.orderDateTime = orderDateTime;
        this.itemsDetails = itemsDetails;
        this.subtotal = subtotal;
        this.taxAmount = taxAmount;
        this.totalAmount = totalAmount;
    }

    public DonutOrder(String orderDateTime, String itemsDetails,
                      double subtotal, double taxAmount, double totalAmount) {
        this(-1, orderDateTime, itemsDetails, subtotal, taxAmount, totalAmount);
    }

    public int getTransactionId() {
        return transactionId;
    }

    public String getOrderDateTime() {
        return orderDateTime;
    }

    public String getItemsDetails() {
        return itemsDetails;
    }

    public double getSubtotal() {
        return subtotal;
    }

    public double getTaxAmount() {
        return taxAmount;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    public void setOrderDateTime(String orderDateTime) {
        this.orderDateTime = orderDateTime;
    }

    public void setItemsDetails(String itemsDetails) {
        this.itemsDetails = itemsDetails;
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    public void setTaxAmount(double taxAmount) {
        this.taxAmount = taxAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }
}
